using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ServicioCuenta
{
    class LlenarTablero
    {
        public Dictionary<String, String> Tablero = new Dictionary<string, string>
        {
            { "Y1", "amarillo" },
            { "Y2", "amarillo" },
            { "Y3",  "amarillo" },
            {"Y4",  "amarillo" },
            {"Y5",  "amarillo" },
            {"Y6",  "amarillo" },
            {"Y7",   "amarillo" },
            {"Y8",   "amarillo" },
            {"Y9",   "amarillo" },
            {"Y10",   "amarillo" },
            {"A1",   "azul"},
            {"A2",   "azul"},
            {"A3",   "azul"},
            {"A4",   "azul"},
            {"A5",   "azul"},
            {"A6",   "azul"},
            {"A7",   "azul"},
            {"A8",   "azul"},
            {"A9",   "azul"},
            {"A10",   "azul"},
            {"L1",   "lavanda"},
            {"L2",   "lavanda"},
            {"L3",   "lavanda"},
            {"L4",   "lavanda"},
            {"L5",   "lavanda"},
            {"L6",   "lavanda"},
            {"L7",   "lavanda"},
            {"L8",   "lavanda"},
            {"L9",   "lavanda"},
            {"L10",   "lavanda"},
            {"M1",   "morado"},
            {"M2",   "morado"},
            {"M3",   "morado"},
            {"M4",   "morado"},
            {"M5",   "morado"},
            {"M6",   "morado"},
            {"M7",   "morado"},
            {"M8",   "morado"},
            {"M9",   "morado"},
            {"M10",   "morado"},
            {"V1",   "verde"},
            {"V2",   "verde"},
            {"V3",   "verde"},
            {"V4",   "verde"},
            {"V5",   "verde"},
            {"V6",   "verde"},
            {"V7",   "verde"},
            {"V8",   "verde"},
            {"V9",   "verde"},
            {"V10",   "verde"},
            {"R1",   "rojo"},
            {"R2",   "rojo"},
            {"R3",   "rojo"},
            {"R4",   "rojo"},
            {"R5",   "rojo"},
            {"R6",   "rojo"},
            {"R7",   "rojo"},
            {"R8",   "rojo"},
            {"R9",   "rojo"},
            {"R10",   "rojo"},
            {"N1",   "vacio"},
            {"N2",   "vacio"},
            {"N3",   "vacio"},
            {"N4",   "vacio"},
            {"N5",   "vacio"},
            {"N6",   "vacio"},
            {"N7",   "vacio"},
            {"N8",   "vacio"},
            {"N9",   "vacio"},
            {"N10",   "vacio"},
            {"N11",  "vacio"},
            {"N12",  "vacio"},
            {"N13",  "vacio"},
            {"N14",  "vacio"},
            {"N15",  "vacio"},
            {"N16",  "vacio"},
            {"N17",  "vacio"},
            {"N18",  "vacio"},
            {"N19",  "vacio"},
            {"N20",  "vacio"},
            {"N21",  "vacio"},
            {"N22",  "vacio"},
            {"N23",  "vacio"},
            {"N24",  "vacio"},
            {"N25",  "vacio"},
            {"N26",  "vacio"},
            {"N27",  "vacio"},
            {"N28",  "vacio"},
            {"N29",  "vacio"},
            {"N30",  "vacio"},
            {"N31",  "vacio"},
            {"N32",  "vacio"},
            {"N33",  "vacio"},
            {"N34",  "vacio"},
            {"N35",  "vacio"},
            {"N36",  "vacio"},
            {"N37",  "vacio"},
            {"N38",  "vacio"},
            {"N39",  "vacio"},
            {"N40",  "vacio"},
            {"N41",  "vacio"},
            {"N42",  "vacio"},
            {"N43",  "vacio"},
            {"N44",  "vacio"},
            {"N45",  "vacio"},
            {"N46",  "vacio"},
            {"N47",  "vacio"},
            {"N48",  "vacio"},
            {"N49",  "vacio"},
            {"N50",  "vacio"},
            {"N51",  "vacio"},
            {"N52",  "vacio"},
            {"N53",  "vacio"},
            {"N54",  "vacio"},
            {"N55",  "vacio"},
            {"N56",  "vacio"},
            {"N57",  "vacio"},
            {"N58",  "vacio"},
            {"N59",  "vacio"},
            {"N60",  "vacio"},
            {"N61",  "vacio"},
        };


     List<Tuple<String, String>> Adyacentes = new List<Tuple<string, string>>
        {
            new Tuple<string, string>("A1", "A2"),
            new Tuple<string, string>("A1", "A5"),
            new Tuple<string, string>("A2", "A3"),
            new Tuple<string, string>("A2", "A6"),
            new Tuple<string, string>("A3", "A4"),
            new Tuple<string, string>("A3", "A7"),
            new Tuple<string, string>("A4", "N1"),
            new Tuple<string, string>("A4", "N6"),
            new Tuple<string, string>("A5", "A6"),
            new Tuple<string, string>("A5", "A8"),
            new Tuple<string, string>("A6", "A7"),
            new Tuple<string, string>("A6", "A9"),
            new Tuple<string, string>("A7", "N6"),
            new Tuple<string, string>("A7", "N12"),
            new Tuple<string, string>("A8", "A9"),
            new Tuple<string, string>("A8", "A10"),
            new Tuple<string, string>("A9", "N12"),
            new Tuple<string, string>("A9", "N19"),
            new Tuple<string, string>("A10", "N19"),
            new Tuple<string, string>("A10", "N27"),
            new Tuple<string, string>("V1", "V2"),
            new Tuple<string, string>("V1", "V3"),
            new Tuple<string, string>("V2", "V4"),
            new Tuple<string, string>("V2", "V5"),
            new Tuple<string, string>("V3", "V5"),
            new Tuple<string, string>("V3", "V6"),
            new Tuple<string, string>("V4", "V7"),
            new Tuple<string, string>("V4", "V8"),
            new Tuple<string, string>("V5", "V8"),
            new Tuple<string, string>("V5", "V9"),
            new Tuple<string, string>("V6", "V9"),
            new Tuple<string, string>("V6", "V10"),
            new Tuple<string, string>("V7", "N1"),
            new Tuple<string, string>("V7", "N2"),
            new Tuple<string, string>("V8", "N2"),
            new Tuple<string, string>("V8", "N3"),
            new Tuple<string, string>("V9", "N3"),
            new Tuple<string, string>("V9", "N4"),
            new Tuple<string, string>("V10", "N4"),
            new Tuple<string, string>("V10", "N5"),
            new Tuple<string, string>("R1", "N5"),
            new Tuple<string, string>("R1", "N11"),
            new Tuple<string, string>("R2", "R1"),
            new Tuple<string, string>("R2", "R5"),
            new Tuple<string, string>("R3", "R2"),
            new Tuple<string, string>("R3", "R5"),
            new Tuple<string, string>("R4", "R3"),
            new Tuple<string, string>("R4", "R7"),
            new Tuple<string, string>("R5", "N11"),
            new Tuple<string, string>("R5", "N18"),
            new Tuple<string, string>("R6", "R5"),
            new Tuple<string, string>("R6", "R8"),
            new Tuple<string, string>("R6", "R5"),
            new Tuple<string, string>("R7", "R6"),
            new Tuple<string, string>("R7", "R9"),
            new Tuple<string, string>("R8", "N18"),
            new Tuple<string, string>("R8", "N26"),
            new Tuple<string, string>("R9", "R8"),
            new Tuple<string, string>("R9", "R10"),
            new Tuple<string, string>("R10", "N26"),
            new Tuple<string, string>("R10", "N35"),
            new Tuple<string, string>("Y1", "N27"),
            new Tuple<string, string>("Y1", "N36"),
            new Tuple<string, string>("Y2", "Y1"),
            new Tuple<string, string>("Y2", "Y3"),
            new Tuple<string, string>("Y3", "N36"),
            new Tuple<string, string>("Y3", "N44"),
            new Tuple<string, string>("Y4", "Y2"),
            new Tuple<string, string>("Y4", "Y5"),
            new Tuple<string, string>("Y5", "Y3"),
            new Tuple<string, string>("Y5", "Y6"),
            new Tuple<string, string>("Y6", "N44"),
            new Tuple<string, string>("Y6", "N51"),
            new Tuple<string, string>("Y7", "Y4"),
            new Tuple<string, string>("Y7", "Y8"),
            new Tuple<string, string>("Y8", "Y5"),
            new Tuple<string, string>("Y8", "Y9"),
            new Tuple<string, string>("Y9", "Y6"),
            new Tuple<string, string>("Y9", "Y10"),
            new Tuple<string, string>("Y10", "N51"),
            new Tuple<string, string>("Y10", "N57"),
            new Tuple<string, string>("L1", "N35"),
            new Tuple<string, string>("L1", "N43"),
            new Tuple<string, string>("L2", "N43"),
            new Tuple<string, string>("L2", "N50"),
            new Tuple<string, string>("L3", "L1"),
            new Tuple<string, string>("L3", "L2"),
            new Tuple<string, string>("L4", "N50"),
            new Tuple<string, string>("L4", "N56"),
            new Tuple<string, string>("L5", "L2"),
            new Tuple<string, string>("L5", "L4"),
            new Tuple<string, string>("L6", "L3"),
            new Tuple<string, string>("L6", "L5"),
            new Tuple<string, string>("L7", "N56"),
            new Tuple<string, string>("L7", "N61"),
            new Tuple<string, string>("L8", "L4"),
            new Tuple<string, string>("L8", "L7"),
            new Tuple<string, string>("L9", "L5"),
            new Tuple<string, string>("L9", "L8"),
            new Tuple<string, string>("L10", "L6"),
            new Tuple<string, string>("L10", "L9"),
            new Tuple<string, string>("M1", "N57"),
            new Tuple<string, string>("M1", "N58"),
            new Tuple<string, string>("M2", "N58"),
            new Tuple<string, string>("M2", "N59"),
            new Tuple<string, string>("M3", "N59"),
            new Tuple<string, string>("M3", "N60"),
            new Tuple<string, string>("M4", "N60"),
            new Tuple<string, string>("M4", "N61"),
            new Tuple<string, string>("M5", "M1"),
            new Tuple<string, string>("M5", "M2"),
            new Tuple<string, string>("M6", "M2"),
            new Tuple<string, string>("M6", "M3"),
            new Tuple<string, string>("M7", "M3"),
            new Tuple<string, string>("M7", "M4"),
            new Tuple<string, string>("M8", "M5"),
            new Tuple<string, string>("M8", "M6"),
            new Tuple<string, string>("M9", "M6"),
            new Tuple<string, string>("M9", "M7"),
            new Tuple<string, string>("M10", "M8"),
            new Tuple<string, string>("M10", "M9"),
            new Tuple<string, string>("N1", "N6"),
            new Tuple<string, string>("N1", "N7"),
            new Tuple<string, string>("N2", "N7"),
            new Tuple<string, string>("N2", "N8"),
            new Tuple<string, string>("N3", "N8"),
            new Tuple<string, string>("N3", "N9"),
            new Tuple<string, string>("N4", "N9"),
            new Tuple<string, string>("N4", "N10"),
            new Tuple<string, string>("N5", "N10"),
            new Tuple<string, string>("N5", "N11"),
            new Tuple<string, string>("N6", "N12"),
            new Tuple<string, string>("N6", "N13"),
            new Tuple<string, string>("N7", "N13"),
            new Tuple<string, string>("N7", "N14"),
            new Tuple<string, string>("N8", "N14"),
            new Tuple<string, string>("N8", "N15"),
            new Tuple<string, string>("N9", "N15"),
            new Tuple<string, string>("N9", "N16"),
            new Tuple<string, string>("N10", "N16"),
            new Tuple<string, string>("N10", "N17"),
            new Tuple<string, string>("N11", "N17"),
            new Tuple<string, string>("N11", "N18"),
            new Tuple<string, string>("N12", "N19"),
            new Tuple<string, string>("N12", "N20"),
            new Tuple<string, string>("N13", "N20"),
            new Tuple<string, string>("N13", "N21"),
            new Tuple<string, string>("N14", "N21"),
            new Tuple<string, string>("N14", "N22"),
            new Tuple<string, string>("N15", "N22"),
            new Tuple<string, string>("N15", "N23"),
            new Tuple<string, string>("N16", "N23"),
            new Tuple<string, string>("N16", "N24"),
            new Tuple<string, string>("N17", "N24"),
            new Tuple<string, string>("N17", "N25"),
            new Tuple<string, string>("N18", "N25"),
            new Tuple<string, string>("N18", "N26"),
            new Tuple<string, string>("N19", "N27"),
            new Tuple<string, string>("N19", "N28"),
            new Tuple<string, string>("N20", "N28"),
            new Tuple<string, string>("N20", "N29"),
            new Tuple<string, string>("N21", "N29"),
            new Tuple<string, string>("N21", "N30"),
            new Tuple<string, string>("N22", "N30"),
            new Tuple<string, string>("N22", "N31"),
            new Tuple<string, string>("N23", "N31"),
            new Tuple<string, string>("N23", "N32"),
            new Tuple<string, string>("N24", "N32"),
            new Tuple<string, string>("N24", "N33"),
            new Tuple<string, string>("N25", "N33"),
            new Tuple<string, string>("N25", "N34"),
            new Tuple<string, string>("N26", "N34"),
            new Tuple<string, string>("N26", "N35"),
            new Tuple<string, string>("N27", "Y1"),
            new Tuple<string, string>("N27", "N36"),
            new Tuple<string, string>("N28", "N36"),
            new Tuple<string, string>("N28", "N37"),
            new Tuple<string, string>("N29", "N37"),
            new Tuple<string, string>("N29", "N38"),
            new Tuple<string, string>("N30", "N38"),
            new Tuple<string, string>("N30", "N39"),
            new Tuple<string, string>("N31", "N39"),
            new Tuple<string, string>("N31", "N40"),
            new Tuple<string, string>("N32", "N40"),
            new Tuple<string, string>("N32", "N41"),
            new Tuple<string, string>("N33", "N41"),
            new Tuple<string, string>("N33", "N42"),
            new Tuple<string, string>("N34", "N42"),
            new Tuple<string, string>("N34", "N43"),
            new Tuple<string, string>("N35", "N43"),
            new Tuple<string, string>("N35", "L1"),
            new Tuple<string, string>("N36", "Y3"),
            new Tuple<string, string>("N36", "N44"),
            new Tuple<string, string>("N37", "N44"),
            new Tuple<string, string>("N37", "N45"),
            new Tuple<string, string>("N38", "N45"),
            new Tuple<string, string>("N38", "N46"),
            new Tuple<string, string>("N39", "N46"),
            new Tuple<string, string>("N39", "N47"),
            new Tuple<string, string>("N40", "N47"),
            new Tuple<string, string>("N40", "N48"),
            new Tuple<string, string>("N41", "N48"),
            new Tuple<string, string>("N41", "N49"),
            new Tuple<string, string>("N42", "N49"),
            new Tuple<string, string>("N42", "N50"),
            new Tuple<string, string>("N43", "N50"),
            new Tuple<string, string>("N43", "L2"),
            new Tuple<string, string>("N44", "Y6"),
            new Tuple<string, string>("N44", "N51"),
            new Tuple<string, string>("N45", "N51"),
            new Tuple<string, string>("N45", "N52"),
            new Tuple<string, string>("N46", "N52"),
            new Tuple<string, string>("N46", "N53"),
            new Tuple<string, string>("N47", "N53"),
            new Tuple<string, string>("N47", "N54"),
            new Tuple<string, string>("N48", "N54"),
            new Tuple<string, string>("N48", "N55"),
            new Tuple<string, string>("N49", "N55"),
            new Tuple<string, string>("N49", "N56"),
            new Tuple<string, string>("N50", "N56"),
            new Tuple<string, string>("N50", "L4"),
            new Tuple<string, string>("N51", "Y10"),
            new Tuple<string, string>("N51", "N57"),
            new Tuple<string, string>("N52", "N57"),
            new Tuple<string, string>("N52", "N58"),
            new Tuple<string, string>("N53", "N58"),
            new Tuple<string, string>("N53", "N59"),
            new Tuple<string, string>("N54", "N59"),
            new Tuple<string, string>("N54", "N60"),
            new Tuple<string, string>("N55", "N60"),
            new Tuple<string, string>("N55", "N61"),
            new Tuple<string, string>("N56", "N61"),
            new Tuple<string, string>("N56", "L7"),
            new Tuple<string, string>("N57", "M1"),
            new Tuple<string, string>("N58", "M1"),
            new Tuple<string, string>("N58", "M2"),
            new Tuple<string, string>("N59", "M2"),
            new Tuple<string, string>("N59", "M3"),
            new Tuple<string, string>("N60", "M3"),
            new Tuple<string, string>("N60", "M4"),
            new Tuple<string, string>("N61", "M4"),
        };

        public bool EsAdyacente(String casilla1, String casilla2)
        {
            var coincidenciasCasilla1 = (from a in Adyacentes where a.Item1 == casilla1 || a.Item2 == casilla1 select a);
            var coincidenciasCasilla2 = (from c in coincidenciasCasilla1 where c.Item1 == casilla2 || c.Item2 == casilla2 select c).Count();
            if (coincidenciasCasilla2 == 1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        private void MoverFicha(String colorTurno, Tuple<String, String> movimiento)
        {
            //Preguntar si la ficha destino es adyacente, Verificar que sea el segundo movimiento del turno del jugador, que el movimiento se realice hacia una casilla vacia y que no se haga clic sobre el mismo botón
       
        }
    }
}
